### ISSUE TITLE
Getting Started dialog and menu item need localization

### ISSUE THREAD

**Issue by bchintx** [edge-code/edge-inspect-extension#15]
The new Getting Started dialog, added by Pull Request #14, needs to be localized.

The dialog appears the very first time you click on the Edge Inspect icon in the toolbar, after a clean install of Edge Code.  After that, you can access the same dialog by clicking on the "Edge Inspect CC" logo in the Edge Inspect extension and then choosing "Getting started..." (which also needs to be localized).

**Comment by bchintx** [comment]
Yay!  Fixed with PR #16.

**Comment by bchintx** [comment]
Will be fixed in EC after pull request # 222 is merged:
https://git.corp.adobe.com/edge/edge-code/pull/222

**Comment by iwehrman** [comment]
Fixed by EC#222. Back to @dalcala to close.

**Comment by julieyuan** [comment]
Hi, I think  the  EdgeInspectInstructionImage.png should also be localized. As far, it is in English.The build I used is 0.95.0-359081392.Please refer to snapshot:
![2](https://f.cloud.github.com/assets/4251563/898867/c66e52d2-fb25-11e2-809b-8da0e0f33771.jpg).

Please help to update it. Thanks in advance.

**Comment by bchintx** [comment]
@larz0 Can you please help create another screenshot using French?

**Comment by larz0** [comment]
@bchintx I'm on it~

**Comment by larz0** [comment]
@bchintx here you go: http://cl.ly/082T2P0x0M0t

**Comment by bchintx** [comment]
Thanks, @larz0.  I've submitted a pull request #17 to add these new, French screenshots to the extension.

**Comment by bchintx** [comment]
Fix merged to EC master in time for Preview 5

**Comment by julieyuan** [comment]
Hi, I still see an English screenshot EdgeInspectInstructionImage.png in today's RC build 0.95.0-359081397 on French OS. So reopen it.

**Comment by julieyuan** [comment]
Still see this happening in today's GM build 0.95.0-359081402 on French OS.

**Comment by bchintx** [comment]
@iwehrman Fixed this with pull request #20.  

Submitted edge-code pull request # 239 to merge into edge-code build.
https://git.corp.adobe.com/edge/edge-code/pull/239

**Comment by iwehrman** [comment]
FBNC to @julieyuan

**Comment by julieyuan** [comment]
Thanks. Fixed in build 0.95.0-359081429. So closing it. Here is the snapshot: 
![capture dcran 2013-08-11 6 47 48 pm](https://f.cloud.github.com/assets/4251563/945049/31858f30-02f2-11e3-82a9-dd95add743e3.png)
